### ISSUE TITLE
Execution failed for task ':city_pickers:compileDebugJavaWithJavac'.

### ISSUE THREAD

**Issue by ericzzhou** [DiscoverForever/learn_flutter#2]
![image](https://user-images.githubusercontent.com/19791685/96212785-297f5600-0faa-11eb-812e-f366dbb74761.png)

**Comment by DiscoverForever** [comment]
![image](https://user-images.githubusercontent.com/16662687/96230151-f6e55580-0fc9-11eb-950c-6d46c8bbafa6.png)
升级city_pickers版本至0.2.0，0.13.0编译打包有问题
