### ISSUE TITLE
大佬，项目编译不过啊

### ISSUE THREAD

**Issue by zhangzhengithubs** [DiscoverForever/learn_flutter#3]
![1606812412(1)](https://user-images.githubusercontent.com/47585226/100717678-55895600-33f5-11eb-8caf-da2b3edecb17.png)

**Comment by DiscoverForever** [comment]
运行一下flutter doctor 把你的本机环境配置贴出来看看。
尝试一下运行
```bash
flutter pub get
flutter run
```
重新安装依赖 运行试试
