### ISSUE TITLE
webView 高度超过5500时

### ISSUE THREAD

**Issue by fudada-521** [DiscoverForever/learn_flutter#6]
请问：
                          // 商品详情
                          Container(
                            width: MediaQuery.of(context).size.width,
                            // TODO Android 超过5500高度会黑屏崩溃
                            height: 5500,
//                            child: WebView(
//                              javascriptMode: JavascriptMode.unrestricted,
//                              initialUrl:
//                                  "https://in.m.jd.com/product/detail/100009177424.html",
//                            ),
                          ),
这个问题怎么解决的？

**Comment by DiscoverForever** [comment]
这个是webview的一个内存溢出bug。
可以给webview设置为屏幕的高度 页面滚动时webview吸顶内部滚动 配合sliver组件实现平滑滚动
